### ISSUE TITLE
Failed to create engine file for RIFEv4.6

### ISSUE THREAD

**Issue by banjaminicc** [AmusementClub/vs-mlrt#10]
```
[11/21/2022-14:01:02] [W] [TRT] onnx2trt_utils.cpp:365: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/21/2022-14:01:02] [W] [TRT] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[11/21/2022-14:01:02] [E] Error[4]: [shuffleNode.cpp::nvinfer1::builder::ShuffleNode::symbolicExecute::391] Error Code 4: Internal Error (/Reshape: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
[11/21/2022-14:01:02] [E] [TRT] ModelImporter.cpp:748: While parsing node number 95 [Pad -> "/Pad_output_0"]:
[11/21/2022-14:01:02] [E] [TRT] ModelImporter.cpp:749: --- Begin node ---
[11/21/2022-14:01:02] [E] [TRT] ModelImporter.cpp:750: input: "/Slice_output_0"
input: "/Cast_5_output_0"
input: ""
output: "/Pad_output_0"
name: "/Pad"
op_type: "Pad"
attribute {
  name: "mode"
  s: "constant"
  type: STRING
}

[11/21/2022-14:01:02] [E] [TRT] ModelImporter.cpp:751: --- End node ---
[11/21/2022-14:01:02] [E] [TRT] ModelImporter.cpp:754: ERROR: ModelImporter.cpp:179 In function parseGraph:
[6] Invalid Node - /Pad
[shuffleNode.cpp::nvinfer1::builder::ShuffleNode::symbolicExecute::391] Error Code 4: Internal Error (/Reshape: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
[11/21/2022-14:01:02] [E] Failed to parse onnx file
[11/21/2022-14:01:02] [I] Finish parsing network model
[11/21/2022-14:01:02] [E] Parsing model failed
[11/21/2022-14:01:02] [E] Failed to create engine from model or file.
[11/21/2022-14:01:02] [E] Engine set up failed
```

Specs are Ryzen 3700x and rtx 3060
Trtexec command :
```
trtexec --fp16 --onnx="rife46_ensembleTrue_opset17.onnx" --minShapes=input:1x8x64x64 --optShapes=input:1x8x720x1280 --maxShapes=input:1x8x1080x1920 --saveEngine=model.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
```

**Comment by WolframRhodium** [comment]
Hi. RIFE requires video dimensions to be multiples of 32. You have to use other scene change detection filters (like `misc.SCDetect`) first and use `std.ModifyFrame` or alike to decide whether to skip frame interpolation. `multipliers` is implemented by passing a clip specifying time point and can be found in `vsmlrt.py`.

**Comment by banjaminicc** [comment]
> Hi. RIFE requires video dimensions to be multiples of 32. You have to use other scene change detection filters (like `misc.SCDetect`) first and use `std.ModifyFrame` or alike to decide whether to skip frame interpolation. `multipliers` is implemented by passing a clip specifying time point and can be found in `vsmlrt.py`.

Thanks!
Im now facing another issue where it says
```
vapoursynth.Error: operator (): no valid optimization profile found
```
when I start tensortrt with my converted model,
any ideas?

**Comment by banjaminicc** [comment]
> Maybe you are using an input video whose dimensions are falling out of the range? I suggest to use the wrapper script first for RIFE.

I couldnt figure out the python script haha
Are there any sample commands?

**Comment by WolframRhodium** [comment]
Its [vsmlrt.py](https://github.com/AmusementClub/vs-mlrt/blob/890dfe2d395c4a702d8d0a7d96615d41216a9624/scripts/vsmlrt.py#L887)

**Comment by banjaminicc** [comment]
I've tried a few things
```
Python exception: name 'Backend' is not defined

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2819, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2820, in vapoursynth._vpy_evaluate
  File "VEAI.vpy", line 15, in <module>
    clip = vsmlrt.RIFE(clip, multi=4, model=46, backend=Backend.TRT, tilesize=[1088,1920])
NameError: name 'Backend' is not defined
```

```
  File "src\cython\vapoursynth.pyx", line 2819, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2820, in vapoursynth._vpy_evaluate
  File "VEAI.vpy", line 15, in <module>
    clip = vsmlrt.RIFE(clip, multi=4, model=46, backend="Backend.TRT", tilesize=[1088,1920])
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vsmlrt.py", line 906, in RIFE
    output0 = RIFEMerge(
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\vsmlrt.py", line 793, in RIFEMerge
    return inference_with_fallback(
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\vsmlrt.py", line 1347, in inference_with_fallback
    raise e
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\vsmlrt.py", line 1328, in inference_with_fallback
    return inference(
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\vsmlrt.py", line 1313, in inference
    raise TypeError(f'unknown backend {backend}')
TypeError: unknown backend Backend.TRT
```

**Comment by banjaminicc** [comment]
> ```python
> clip = vsmlrt.RIFE(clip, multi=4, model=46, backend=vsmlrt.Backend.TRT(fp16=True))
> ```

This worked!
thanks
It'll grab the rife46 model from %appdata%/vapoursynth/plugins/model/rife
i presume?

**Comment by banjaminicc** [comment]
```
[11/21/2022-15:57:47] [W] Could not read timing cache from: C:/Users//AppData/Roaming/VapourSynth/plugins64\models\rife\rife_v4.6.onnx.1088x1920_fp16_workspace128_trt-8501_NVIDIA-GeForce-RTX-3060_a0fc9148.engine.cache. A new timing cache will be generated and written.
[11/21/2022-15:57:47] [E] Error[4]: [network.cpp::nvinfer1::Network::validate::3076] Error Code 4: Internal Error (input: for dimension number 1 in profile 0 does not match network definition (got min=11, opt=11, max=11), expected min=opt=max=8).)
[11/21/2022-15:57:47] [E] Error[2]: [builder.cpp::nvinfer1::builder::Builder::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[11/21/2022-15:57:47] [E] Engine could not be created from network
[11/21/2022-15:57:47] [E] Building engine failed
[11/21/2022-15:57:47] [E] Failed to create engine from model or file.
[11/21/2022-15:57:47] [E] Engine set up failed
```
It crashed half way :(

**Comment by WolframRhodium** [comment]
It seems that you are not using the rife model provided in this repository?

**Comment by banjaminicc** [comment]
> It seems that you are not using the rife model provided in this repository?

I'm using the one in vsgan-tensorrt-docker
It's the rife46 model with ensemble enabled

**Comment by WolframRhodium** [comment]
then you should use his wrapper [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/fe2f88855cb2ca3f683058fd062e316467aed6a6/src/rife_trt.py#L8)

**Comment by banjaminicc** [comment]
It also seems like his wrapper doesnt help with model training?
which I'm stuck on right now

**Comment by banjaminicc** [comment]
> what do you mean for model training? fine tuning or training rife from scratch?

Oh sorry not training
engine generation

**Comment by WolframRhodium** [comment]
yep, it should be 
`trtexec --fp16 --onnx="rife46_ensembleTrue_opset17.onnx" --shapes=input:1x8x1088x1920 --saveEngine=model.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly`

**Comment by banjaminicc** [comment]
> yep, it should be `trtexec --fp16 --onnx="rife46_ensembleTrue_opset17.onnx" --shapes=input:1x8x1088x1920 --saveEngine=model.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly`

Now I'm getting this error
```
vapoursynth.Error: operator (): expects 8 input planes
```
the engine trained succesfullly and I'm using vsmlrt.py

**Comment by WolframRhodium** [comment]
you should ask vsgan-tensorrt-docker's author on use of his models. i should not reply here

**Comment by WolframRhodium** [comment]
this error is related to the onnx model provided by him, you should use his wrapper [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/fe2f88855cb2ca3f683058fd062e316467aed6a6/src/rife_trt.py#L8)

**Comment by AkarinVS** [comment]
Due to the complexity of AI runtimes and limited resources, unfortunately we are only able to support the bundled filters.
If you use your own onnx models, we can only provide some generic hints and not debugging support.
Apologies for inconvenience.
