### ISSUE TITLE
vsmigx terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by abihf** [AmusementClub/vs-mlrt#109]
I'm trying to run realesrgan with vsmigx, but it always crash.

```gdb
#0  0x000076edbc1a6c68 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x76eb56c00640 (LWP 342))]
(gdb) bt
#0  0x000076edbc1a6c68 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000076edb7d8d890 in vs_bitblt (dstp=0x76ec70bf8000, dst_stride=7680, srcp=0x76eb51400080, 
    src_stride=7680, row_size=7680, height=1088) at /usr/include/vapoursynth/VSHelper.h:149
#2  0x000076edb7d8fa2e in vsMIGXGetFrame (n=1, activationReason=2, instanceData=0x5be2a71516d0, 
    frameData=0x76eb44000e40, frameCtx=0x76eb44000ba0, core=0x5be2a1583600, 
    vsapi=0x76edbb67ac60 <vs_internal_vsapi3>) at /workspace/vs-mlrt/vsmigx/vs_migraphx.cpp:529
#3  0x000076edbb5ac0d1 in VSThreadPool::runTasks(std::atomic<bool>&) () from /lib/libvapoursynth.so
#4  0x000076edbc4dc253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000076edbc094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x000076edbc126850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by WolframRhodium** [comment]
You could run it before
https://github.com/AmusementClub/vs-mlrt/issues/85#issuecomment-1975179804
is this an issue with the new migx or vsmigx?

**Comment by abihf** [comment]
sorry, I was stupid. Forgot to convert to RGBH before inference.

**Comment by WolframRhodium** [comment]
I'm sorry that I forget to add this check.
