### ISSUE TITLE
Tile error with Rife 4.26 on non standard dimension videos

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#112]
```
Failed to evaluate the script:
Python exception: vsmlrt.RIFEMerge: tile size must be divisible by 64 (192, 160)

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3365, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3366, in vapoursynth._vpy_evaluate
File "C:\Users\admin\AppData\Local\Temp\tempPreviewVapoursynthFile11_44_02_151.vpy", line 63, in 
clip = vsmlrt.RIFE(clip, multi=Fraction(2), model=426, backend=Backend.ORT_DML(fp16=False,device_id=0)) # new fps: 28.96
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1215, in RIFE
output0 = RIFEMerge(
^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1049, in RIFEMerge
raise ValueError(
ValueError: vsmlrt.RIFEMerge: tile size must be divisible by 64 (192, 160)

```

Latest Hybrid dev and vsmlrt addon.
Input file dimensions are realy small
Width  : 176 pixels 
Height : 144 pixels

rife 4.25 and lower doesnt have this problem with such small input dimensions.

**Comment by WolframRhodium** [comment]
The exception is raised because rife 4.26 upgrades the architecture. (https://github.com/hzwer/Practical-RIFE/issues/109#issuecomment-2366812473)

You should not expect the limitation on tile size to be stable for the v1 implementation. The v2 implementation handles this automatically.
