### ISSUE TITLE
[local-issue] Incompatible dimensions when using ml_PP-OCRv3_det.onnx

### ISSUE THREAD

**Issue by dtlnor** [AmusementClub/vs-mlrt#14]
我在尝试用ocr模型的时候遇到了以下的报错：
```
2022-12-08 18:16:53.514: ERROR: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (Add_43) Op (Add) [ShapeInferenceError] Incompatible dimensions
Traceback (most recent call last):
  File "C:\Users\dtlnor\Downloads\Compressed\vapoursynth_portable_22H2p_full\test.vpy", line 48, in <module>
    OCRTest(src32, tiles=1),
  File "C:\Users\dtlnor\Downloads\Compressed\vapoursynth_portable_22H2p_full\test.vpy", line 32, in OCRTest
    res = inference(
  File "C:\Users\dtlnor\Downloads\Compressed\vapoursynth_portable_22H2p_full\vapoursynth\VapourSynthScripts\vsmlrt.py", line 908, in inference
    clip = core.ort.Model(
  File "src\cython\vapoursynth.pyx", line 2727, in vapoursynth.Function.__call__
vapoursynth.Error: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (Add_43) Op (Add) [ShapeInferenceError] Incompatible dimensions
```

info:
```
HArdware:
CPU: AMD Ryzen 9 5900X
GPU: RTX 4090

System:
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1645
```

`vs version`: [vapoursynth_portable_22H2p_full](https://github.com/AmusementClub/tools/releases/tag/2022H2p)
没客制化任何其他东西

script:
```python
import vapoursynth as vs
import sys
import havsfunc as haf
import mvsfunc as mvf
import descale
import nnedi3_resample as nnrs
import math
import enum
import numpy as np

core = vs.core

def OCRTest(clip: vs.VideoNode, tiles = 1):
	from vsmlrt import Backend
	from vsmlrt import inference
	from vsmlrt import calc_tilesize
	from vsmlrt import init_backend

	(tile_w, tile_h), (overlap_w, overlap_h) = calc_tilesize(
        tiles=tiles, tilesize=None,
        width=clip.width, height=clip.height,
        multiple=1,
        overlap_w=0, overlap_h=0
    )

	res = inference(
        [clip],
        network_path=r"somewhere\ml_PP-OCRv3_det.onnx",
	    overlap=(overlap_w, overlap_h),
        tilesize=(tile_w, tile_h),
        backend=Backend.ORT_CUDA()
    )

	return res

sourcename = r"test.mp4"
source= core.lsmas.LWLibavSource(sourcename)

src32 = mvf.ToRGB(source, depth= 32, sample=1)

mvf.Preview([
    OCRTest(src32, tiles=1), 
    ], depth=8).set_output()
```

请问是输入格式错误了吗？（比如需要某个multiple之类的？）还是不应该以rgbs输入？

**Comment by WolframRhodium** [comment]
边长要是64的倍数

**Comment by dtlnor** [comment]
原来如此，能够运行了，感谢。
