### ISSUE TITLE
input pixel bitdepth not supported with fmtc.resample

### ISSUE THREAD

**Issue by ViRb3** [AmusementClub/vs-mlrt#32]
I have the following:
```python
backend = Backend.TRT(
    fp16=True,
    output_format=1,
    force_fp16=True,
    device_id=0,
    tf32=False,
    use_cudnn=False,
    num_streams=2,
    workspace=None,
    use_cuda_graph=True,
)
clip = core.ffms2.Source(
    source="/path/to/file.mp4"
    cache=False,
)
clip = core.resize.Lanczos(
    clip,
    format=vs.RGBS,
)
clip = RealESRGANv2(
    clip,
    model=RealESRGANv2Model.animevideov3,
    backend=backend,
    scale=2,
)
```
I get a crash like:
```
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
  File "inference.py", line 179, in <module>
    clip = RealESRGANv2(
  File "vsmlrt\vsmlrt.py", line 517, in RealESRGAN
    clip = core.fmtc.resample(clip, scale=rescale, kernel="lanczos", taps=4, fh=1/rescale, fv=1/rescale)
  File "src\cython\vapoursynth.pyx", line 2612, in vapoursynth.Function.__call__
vapoursynth.Error: resample: input pixel bitdepth not supported.
```
I can work around by omitting scale and then manually rescaling like:
```python
clip = core.resize.Lanczos(clip, clip.width/2, clip.height/2)
```
Why is this happening though?

Thanks

**Comment by NSQY** [comment]
> Why is this happening though?
> 
> Thanks

This may be caused by https://github.com/EleonoreMizo/fmtconv/issues/38. It has been fixed but but a new release has not yet been pushed.

**Comment by ViRb3** [comment]
Makes sense, thank you! @WolframRhodium in your fix commit above, can I ask why you are doing:
```python
clip = core.resize.Point(clip, format=vs.RGBS)
clip = core.fmtc.resample(clip, scale=rescale, kernel="lanczos", taps=4, fh=1/rescale, fv=1/rescale)
clip = core.resize.Point(clip, format=vs.RGBH)
```
Instead of all at once with just `core.resize.Lanczos`? Is there any benefit to using `fmtconv` instead of the built-in functions?

**Comment by WolframRhodium** [comment]
Because the [`cv2.resize`](https://github.com/xinntao/Real-ESRGAN/blob/5ca1078535923d485892caee7d7804380bfc87fd/realesrgan/utils.py#L257-L261) used by the author is not an ordinary lanczos-4 resize (downsampling without anti-aliasing) and has to implemented in fmtc.
