### ISSUE TITLE
Vsov plugin how to use?

### ISSUE THREAD

**Issue by Usulyre** [AmusementClub/vs-mlrt#47]
Any examples on how to use vsov vapoursynth plugin?

Are there any examples pertaining to motion interpolation?

Thank you in advance.

**Comment by WolframRhodium** [comment]
Hello.

If you would like to use RIFE for motion interpolation, a snippet could be
```python3
import vapoursynth as vs
from vapoursynth import core
import vsmlrt
from vsmlrt import RIFEModel, Backend

backend = Backend.OV_CPU() # or `Backend.OV_GPU(fp16=True)` on Intel GPUs

src = core.lsmas.LWLibavSource("source.mp4")
ph = (src.height + 31) // 32 * 32 - src.height
pw = (src.width  + 31) // 32 * 32 - src.width
padded = src.std.AddBorders(right=pw, bottom=ph).resize.Bicubic(format=vs.RGBH, matrix_in_s="709")
flt = vsmlrt.RIFE(padded, model=RIFEModel.v4_4, backend=backend)
res = flt.resize.Bicubic(format=vs.YUV420P8, matrix_s="709").std.Crop(right=pw, bottom=ph)
res.set_output()
```

In general, you could use the vsov plugin through the `vsmlrt.inference()` wrapper from vsmlrt.py with `Backend.OV_CPU` or `Backend.OV_GPU` backends, or the plugin directly by providing the video source clip and the  ai model in the onnx format to the `core.ov.Model()` interface.

**Comment by Usulyre** [comment]
> Hello.
> 
> If you would like to use RIFE for motion interpolation, a snippet could be
> 
> ```python
> import vapoursynth as vs
> from vapoursynth import core
> import vsmlrt
> from vsmlrt import RIFEModel, Backend
> 
> backend = Backend.OV_CPU() # or `Backend.OV_GPU(fp16=True)` on Intel GPUs
> 
> src = core.lsmas.LWLibavSource("source.mp4")
> ph = (src.height + 31) // 32 * 32 - src.height
> pw = (src.width  + 31) // 32 * 32 - src.width
> padded = src.std.AddBorders(right=pw, bottom=ph).resize.Bicubic(format=vs.RGBH, matrix_in_s="709")
> flt = vsmlrt.RIFE(padded, model=RIFEModel.v4_4, backend=backend)
> res = flt.resize.Bicubic(format=vs.YUV420P8, matrix_s="709").std.Crop(right=pw, bottom=ph)
> res.set_output()
> ```
> 
> In general, you could use the vsov plugin through the `vsmlrt.inference()` wrapper from vsmlrt.py with `Backend.OV_CPU` or `Backend.OV_GPU` backends, or the plugin directly by providing the video source clip and the ai model in the onnx format to the `core.ov.Model()` interface.

Thanks for  your reply.

I want to try it using this:

https://github.com/CrendKing/avisynth_filter

Specifically the vapoursynth filter.

Can you give me an example of that last part:

" or the plugin directly by providing the video source clip and the ai model in the onnx format to the core.ov.Model() interface."

Thanks again.

**Comment by WolframRhodium** [comment]
```python3
flt = core.ov.Model(padded, "path_to_onnx")
```

**Comment by hooke007** [comment]
But it seems no full fp16 support in ov backend?
```
Python exception: operator (): expects clip with type fp32

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "test.py", line 38, in <module>
    flt = vsmlrt.RIFE(padded, model=RIFEModel.v4_6, backend=backend)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TOOLS\mpv-lazy\vsmlrt.py", line 1024, in RIFE
    output0 = RIFEMerge(
              ^^^^^^^^^^
  File "C:\TOOLS\mpv-lazy\vsmlrt.py", line 898, in RIFEMerge
    return inference_with_fallback(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TOOLS\mpv-lazy\vsmlrt.py", line 1539, in inference_with_fallback
    raise e
  File "C:\TOOLS\mpv-lazy\vsmlrt.py", line 1518, in inference_with_fallback
    return _inference(
           ^^^^^^^^^^^
  File "C:\TOOLS\mpv-lazy\vsmlrt.py", line 1436, in _inference
    clip = core.ov.Model(
           ^^^^^^^^^^^^^^
  File "src\cython\vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: operator (): expects clip with type fp32
```

**Comment by WolframRhodium** [comment]
fp16 clip is only supported with TRT.

**Comment by hooke007** [comment]
I think you misunderstood sth...
I was testing the script you wrote https://github.com/AmusementClub/vs-mlrt/issues/47#issuecomment-1530715851

> use OV_GPU(fp16=True) instead.

Same error.

**Comment by WolframRhodium** [comment]
```python3
import vapoursynth as vs
from vapoursynth import core
import vsmlrt
from vsmlrt import RIFEModel, Backend

backend = Backend.OV_CPU() # or `Backend.OV_GPU(fp16=True)` on Intel GPUs

src = core.lsmas.LWLibavSource("source.mp4")
ph = (src.height + 31) // 32 * 32 - src.height
pw = (src.width  + 31) // 32 * 32 - src.width
padded = src.std.AddBorders(right=pw, bottom=ph).resize.Bicubic(format=vs.RGBS, matrix_in_s="709")
flt = vsmlrt.RIFE(padded, model=RIFEModel.v4_4, backend=backend)
res = flt.resize.Bicubic(format=vs.YUV420P8, matrix_s="709").std.Crop(right=pw, bottom=ph)
res.set_output()
```

**Comment by Usulyre** [comment]
> ```python
> flt = core.ov.Model(padded, "path_to_onnx")
> ```
> 
> I will not answer questions related to other repositories.

Ok.

My sample script:

import vapoursynth as vs
from vapoursynth import core


import vsmlrt
from vsmlrt import RIFEModel, Backend
core = vs.core
ret = VpsFilterSource
backend = vsmlrt.Backend.TRT(fp16=True)

ret = core.resize.Bicubic(clip=ret, format=vs.RGBS, matrix_in_s="470bg", range_s="full")
ret = vsmlrt.RIFE(clip=ret, multi=5, model=RIFEModel.v4_6, backend=backend)


output_ret = core.resize.Bicubic(clip=ret,format=vs.YUV420P8, matrix_s="709")

output_ret.set_output()

**Comment by Usulyre** [comment]
I decided to use this because I have a GTX 1660.

My next question is how do I use a different model like "rife_v4.6_ensemble.onnx"

What do I put in the value for the script to specify that external model?  "model=             "

**Comment by hooke007** [comment]
When you import a function from a module, you should know how to get all its available flags.
For `vsmlrt.RIFE` , you could found all flags here in the script:
https://github.com/AmusementClub/vs-mlrt/blob/cf2bfbffe10361990e2cdcaada78c6a34046c8e6/scripts/vsmlrt.py#L961-L971
To use rife_v4.6, just use `model=46` instead.

**Comment by WolframRhodium** [comment]
> I decided to use this because I have a GTX 1660.
> 
> My next question is how do I use a different model like "rife_v4.6_ensemble.onnx"
> 
> What do I put in the value for the script to specify that external model? "model= "

```python3
ret = vsmlrt.RIFE(clip=ret, multi=5, model=RIFEModel.v4_6, backend=backend, ensemble=True)
```

**Comment by Usulyre** [comment]
> When you import a function from a module, you should know how to get all its available flags. For `vsmlrt.RIFE` , you could found all flags here in the script:
> 
> https://github.com/AmusementClub/vs-mlrt/blob/cf2bfbffe10361990e2cdcaada78c6a34046c8e6/scripts/vsmlrt.py#L961-L971
> 
> To use rife_v4.6, just use `model=46` instead.

Is this the same as the model i found from rife_v2?

rife_v4.6_ensemble.onnx

downloaded ext-models.v13.1

**Comment by Usulyre** [comment]
> ```python
> ensemble=True
> ```

Ok,

How do I then specify the one from the rife_v2 folder in the  script?

**Comment by hooke007** [comment]
`_implementation=2`

**Comment by Shinobuos** [comment]
Put up a blessed guide to install or compile these functions on Linux for the love of whatever deity they create.
