### ISSUE TITLE
v4.12_lite model not working,...

### ISSUE THREAD

**Issue by Selur** [AmusementClub/vs-mlrt#71]
I wanted to try the new lite model (I downloaded the model and updated vsmlrt.py).

Using v4.12_lite
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_CUDA(fp16=False,device_id=0)) # new fps: 50`,
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_CUDA(fp16=True,device_id=0)) # new fps: 50`,
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_CPU(fp16=False)) # new fps: 50`,
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_CPU(fp16=True)) # new fps: 50`,
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_DML(fp16=False,device_id=0)) # new fps: 50`,
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.ORT_DML(fp16=True,device_id=0)) # new fps: 50`,
all fail with:
```
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1474, in _inference
clip = core.ort.Model(
^^^^^^^^^^^^^^^
File "src\cython\vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: operator (): expects 7 input planes
```
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.TRT(fp16=True,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1, workspace=1 << 30,builder_optimization_level=3)) # new fps: 50`
fails with: 
```
<!--StartFragment--><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
</style></head><body>

2023-11-17 15:29:04.965 Failed to evaluate the script:Python exception: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_231117_152900.logTraceback (most recent call last):File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluateFile "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluateFile "J:\tmp\tempPreviewVapoursynthFile15_28_59_887.vpy", line 42, in File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1074, in RIFEoutput0 = RIFEMerge(^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 948, in RIFEMergereturn inference_with_fallback(^^^^^^^^^^^^^^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1613, in inference_with_fallbackraise eFile "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1592, in inference_with_fallbackreturn _inference(^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1528, in _inferenceengine_path = trtexec(^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1351, in trtexecraise RuntimeError(f"trtexec execution fails, log has been written to {log_filename}")RuntimeError: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_231117_152900.log
--
2023-11-17 15:29:05.144 [VSE Server]: incoming connection [VSE Server]: ConnectedState [VSE Server]: socket is ready to be read [VSE Server]: connection open: true [VSE Server]: connection readable: true [VSE Server] - Message received: changeTo ### J:\tmp\tempPreviewVapoursynthFile15_29_03_305.vpy ### off#0#0#0#0
2023-11-17 15:29:09.961 Failed to evaluate the script:Python exception: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_231117_152905.logTraceback (most recent call last):File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluateFile "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluateFile "J:\tmp\tempPreviewVapoursynthFile15_29_03_305.vpy", line 42, in clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.TRT(fp16=True,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1, workspace=1 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1074, in RIFEoutput0 = RIFEMerge(^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 948, in RIFEMergereturn inference_with_fallback(^^^^^^^^^^^^^^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1613, in inference_with_fallbackraise eFile "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1592, in inference_with_fallbackreturn _inference(^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1528, in _inferenceengine_path = trtexec(^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1351, in trtexecraise RuntimeError(f"trtexec execution fails, log has been written to {log_filename}")RuntimeError: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_231117_152905.log

</body></html><!--EndFragment-->
```
[trtexec_231117_152905.log](https://github.com/AmusementClub/vs-mlrt/files/13392959/trtexec_231117_152905.log)
`clip = vsmlrt.RIFE(clip, model=4121, backend=Backend.TRT(fp16=False,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1, workspace=1 << 30,builder_optimization_level=3)) # new fps: 50`
fails with:
```
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 948, in RIFEMerge
return inference_with_fallback(
^^^^^^^^^^^^^^^^^^^^^^^^
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1613, in inference_with_fallback
raise e
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1592, in inference_with_fallback
return _inference(
^^^^^^^^^^^
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1528, in _inference
engine_path = trtexec(
^^^^^^^^
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1351, in trtexec
raise RuntimeError(f"trtexec execution fails, log has been written to {log_filename}")
RuntimeError: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_231117_153139.log
```
[trtexec_231117_153139.log](https://github.com/AmusementClub/vs-mlrt/files/13392980/trtexec_231117_153139.log)

Did I miss something I should have updated, or is this simply broken atm. ?

Cu Selur

Ps.: normal v4.12 does work fine.
PPs.: same when enabling Ensamble and/or using v2

**Comment by WolframRhodium** [comment]
I guess you put v1 and v2 models in the opposite folder.

**Comment by Selur** [comment]
DUH,... you are correct! Now it works. 👍 👍 
Thanks a lot!
