### ISSUE TITLE
FBCNN jpeg artifact reduction support

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#83]
Hi!
I was trying to convert an FBCNN model for JPEG artifact removal using Chainner, and successfully converted it to ONNX. Unfortunately, VS-MLRT seems not to support it, and I'm getting the following error: "
2024-02-14 11:15:07.022
Failed to evaluate the script:
Python exception: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (/Add_33) Op (Add) [ShapeInferenceError] Incompatible dimensions

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
File "G:\HYBRIDtemp\tempPreviewVapoursynthFile11_15_05_244.vpy", line 54, in 
clip = vsmlrt.inference([clip],network_path="C:/Users/admin/Pictures/FBCNN ncnn/fbcnn_color-sim.onnx", backend=Backend.ORT_DML(fp16=True,device_id=0,num_streams=1))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1950, in inference
return inference_with_fallback(
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1926, in inference_with_fallback
raise e
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1905, in inference_with_fallback
return _inference(
^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1772, in _inference
clip = core.ort.Model(
^^^^^^^^^^^^^^^
File "src\cython\vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (/Add_33) Op (Add) [ShapeInferenceError] Incompatible dimensions

". 
Is there any way to add support for the FBCNN real color model? It does a fantastic job! Thanks!

**Comment by WolframRhodium** [comment]
Could you upload your onnx model here?

**Comment by zelenooki87** [comment]
here you are:
[https://mega.nz/folder/M9IUWSaL#4tjTY3ElnX9ClQp6WBBOKg](url)

**Comment by WolframRhodium** [comment]
The error is because your model requires `tile_size % 8 == 5` on each dimension.

Besides, it is not supported by vs-mlrt backends by default because it requires fp16 I/O and has already been quantized. You need to export to ONNX without quantization (i.e. with fp32 I/O and weights).

**Comment by zelenooki87** [comment]
Will try, and inform you.

**Comment by zelenooki87** [comment]
Same error again: 
`

2024-02-14 12:34:57.404
Failed to evaluate the script:
Python exception: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (/Add_33) Op (Add) [ShapeInferenceError] Incompatible dimensions

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
File "G:\HYBRIDtemp\tempPreviewVapoursynthFile12_34_54_642.vpy", line 54, in 
clip = vsmlrt.inference([clip],network_path="C:/Users/admin/Pictures/FBCNN 32bit/fbcnn_color.onnx", backend=Backend.ORT_DML(fp16=False,device_id=0,num_streams=1))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1950, in inference
return inference_with_fallback(
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1926, in inference_with_fallback
raise e
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1905, in inference_with_fallback
return _inference(
^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1772, in _inference
clip = core.ort.Model(
^^^^^^^^^^^^^^^
File "src\cython\vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: operator (): 'ortapi->CreateSessionFromArray( d->environment, std::data(onnx_data), std::size(onnx_data), session_options, &resource.session )' failed: Node (/Add_33) Op (Add) [ShapeInferenceError] Incompatible dimensions

`
fp32 model [https://mega.nz/file/I5xSBBZB#ivYqHUGNXZMIJeZ5NPijlv-ME-a8QRxYHCMdmPiFnT8](url)

Original pytorch fbcnn models are here
[https://github.com/jiaxi-jiang/FBCNN/releases/tag/v1.0](url)

**Comment by WolframRhodium** [comment]
> The error is because your model requires `tile_size % 8 == 3` on each dimension.

**Comment by zelenooki87** [comment]
Unfortunately, I don't have enough knowledge to create such a model. Would it be possible to integrate the FBCNN function for decompression removal into the VS-MLRT module? Thank you.

**Comment by zelenooki87** [comment]
Okay, thanks for answer
