### ISSUE TITLE
Could not convert FemaSR 2x onnx to tensorrt. Directml working ok (both 32 & 16)

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#89]
FemaSR x2 model converted from pytorch in chainner
[https://mega.nz/file/7ElWBIRT#mZ2voIv3w90J1TH_EL3DcdW5Qgiu9HgeTItgDjus5DQ](url)

`
2024-03-31 13:33:32.622
Failed to evaluate the script:
Python exception: trtexec execution fails, log has been written to C:\Users\mika\AppData\Local\Temp\trtexec_240331_133308.log

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
File "C:\Users\mika\AppData\Local\Temp\tempPreviewVapoursynthFile13_33_07_920.vpy", line 42, in 
clip = vsmlrt.inference([clip],network_path="E:/MODELI ZA HYBRID TRT/FeMaSR_SRX2_model_g.onnx", backend=Backend.TRT(fp16=True,device_id=0,num_streams=1,verbose=True,use_cuda_graph=False, workspace=1073741824,builder_optimization_level=1))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2060, in inference
return inference_with_fallback(
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2036, in inference_with_fallback
raise e
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2015, in inference_with_fallback
return _inference(
^^^^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1923, in _inference
engine_path = trtexec(
^^^^^^^^
File "C:/Program Files/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1625, in trtexec
raise RuntimeError(f"trtexec execution fails, log has been written to {log_filename}")
RuntimeError: trtexec execution fails, log has been written to C:\Users\mika\AppData\Local\Temp\trtexec_240331_133308.log

`

Is there a solution to speed up inference time? :)
Thanks

**Comment by WolframRhodium** [comment]
Please upload the log.

**Comment by zelenooki87** [comment]
here you are:
[hybridvsmlrt.zip](https://github.com/AmusementClub/vs-mlrt/files/14816021/hybridvsmlrt.zip)

**Comment by WolframRhodium** [comment]
The file only contains partial logs. `--builderOptimizationLevel=1` may cause problems, consider compilation without it at first.
