### ISSUE TITLE
SwinIR only fp32?

### ISSUE THREAD

**Issue by Selur** [AmusementClub/vs-mlrt#91]
Did a few tests with the new SwinIR model support.
I tested the SwinIR filtering (only; no scaling) models and noticed, that they fail for fp16=true, is that a known restriction?
Can you confirm this, or is it probably something with my setup?

**Comment by WolframRhodium** [comment]
It should support fp16 as shown in the benchmark section.

**Comment by Selur** [comment]
using:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
import site
import sys
import os
core = vs.core
# Import scripts folder
scriptPath = 'F:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
os.environ["CUDA_MODULE_LOADING"] = "LAZY"
# loading plugins
core.std.LoadPlugin(path="F:/Hybrid/64bit/vs-mlrt/vstrt.dll")
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/LSMASHSource.dll")
# Import scripts
from importlib.machinery import SourceFileLoader
vsmlrt = SourceFileLoader('vsmlrt', 'F:/Hybrid/64bit/vs-mlrt/vsmlrt.py').load_module()
# Source: 'G:\TestClips&Co\files\test.avi'
# Current color space: YUV420P8, bit depth: 8, resolution: 640x352, frame rate: 25fps, scanorder: progressive, yuv luminance scale: limited, matrix: 470bg
# Loading G:\TestClips&Co\files\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/files/test.avi" , format="YUV420P8" , stream_index=0 , cache=0 , prefer_hw=0)
frame = clip.get_frame(0)
# Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
# setting color transfer (170), if it is not set.
if '_Transfer' not in frame.props or not frame.props['_Transfer']:
  clip = core.std.SetFrameProps(clip, _Transfer=6)
# setting color primaries info (to 470), if it is not set.
if '_Primaries' not in frame.props or not frame.props['_Primaries']:
  clip = core.std.SetFrameProps(clip, _Primaries=5)
# setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip , prop="_ColorRange" , intval=1)
# making sure frame rate is set to 25fps
clip = core.std.AssumeFPS(clip=clip , fpsnum=25 , fpsden=1)
# making sure the detected scan type is set
clip = core.std.SetFrameProp(clip=clip , prop="_FieldBased" , intval=0)# progressive
from vsmlrt import Backend
# adjusting color space from YUV420P8 to RGBS for vsSwinIRmlrt
clip = core.resize.Bicubic(clip=clip , format=vs.RGBS , matrix_in_s="470bg" , range_s="limited")
# denosing using SwinIR (mlrt)
clip = vsmlrt.SwinIR(clip, model=17 , overlap=16 , backend=Backend.TRT(fp16=True, device_id=0, verbose=True, use_cuda_graph=False , num_streams=1 , workspace=1, builder_optimization_level=3))
# adjusting output color from: RGBS to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip , format=vs.YUV420P10 , matrix_s="470bg" , range_s="limited" , dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip , fpsnum=25 , fpsden=1)
# output
clip.set_output()
```
in vsViewer, I see a green screen and the following error:
```
<!--StartFragment--><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
</style></head><body>

2024-04-24 14:50:21.349 Failed to evaluate the script:Python exception: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_240424_144814.logTraceback (most recent call last):File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluateFile "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluateFile "C:\Users\Selur\Desktop\test.vpy", line 41, in clip = vsmlrt.SwinIR(clip, model=17 , overlap=16 , backend=Backend.TRT(fp16=True, device_id=0, verbose=True, use_cuda_graph=False , num_streams=1 , workspace=1, builder_optimization_level=3))^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1615, in SwinIRclip = inference_with_fallback(^^^^^^^^^^^^^^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2397, in inference_with_fallbackraise eFile "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2376, in inference_with_fallbackreturn _inference(^^^^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 2272, in _inferenceengine_path = trtexec(^^^^^^^^File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1920, in trtexecraise RuntimeError(f"trtexec execution fails, log has been written to {log_filename}")RuntimeError: trtexec execution fails, log has been written to C:\Users\Selur\AppData\Local\Temp\trtexec_240424_144814.log
--


</body></html><!--EndFragment-->
```
-> [trtexec_240424_144814.log](https://github.com/AmusementClub/vs-mlrt/files/15094464/trtexec_240424_144814.log)

**Comment by Selur** [comment]
ARGH, copy&paste accidentally set workspace = 1
using:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
import site
import sys
import os
core = vs.core
# Import scripts folder
scriptPath = 'F:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
os.environ["CUDA_MODULE_LOADING"] = "LAZY"
# loading plugins
core.std.LoadPlugin(path="F:/Hybrid/64bit/vs-mlrt/vstrt.dll")
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/LSMASHSource.dll")
# Import scripts
from importlib.machinery import SourceFileLoader
vsmlrt = SourceFileLoader('vsmlrt', 'F:/Hybrid/64bit/vs-mlrt/vsmlrt.py').load_module()
# Source: 'G:\TestClips&Co\files\test.avi'
# Current color space: YUV420P8, bit depth: 8, resolution: 640x352, frame rate: 25fps, scanorder: progressive, yuv luminance scale: limited, matrix: 470bg
# Loading G:\TestClips&Co\files\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/files/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
frame = clip.get_frame(0)
# Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
# setting color transfer (170), if it is not set.
if '_Transfer' not in frame.props or not frame.props['_Transfer']:
  clip = core.std.SetFrameProps(clip, _Transfer=6)
# setting color primaries info (to 470), if it is not set.
if '_Primaries' not in frame.props or not frame.props['_Primaries']:
  clip = core.std.SetFrameProps(clip, _Primaries=5)
# setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# making sure frame rate is set to 25fps
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# making sure the detected scan type is set
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0) # progressive
from vsmlrt import Backend
# adjusting color space from YUV420P8 to RGBS for vsSwinIRmlrt
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="limited")
# denosing using SwinIR (mlrt)
clip = vsmlrt.SwinIR(clip, model=17, overlap=16, backend=Backend.TRT(fp16=True,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1, workspace=1073741824,builder_optimization_level=3))
# adjusting output color from: RGBS to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P10, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# output
clip.set_output()
```
I get no error, but a green screen as output.

**Comment by WolframRhodium** [comment]
Please try removing the `workspace=1<<30` argument. By default it uses the maximum available workspace.

**Comment by Selur** [comment]
Without the workspace argument, get no errors but a green screen.

**Comment by WolframRhodium** [comment]
Thanks, it seems that all SwinIR-M and SwinIR-L models are broken with fp16. Let me check it.

**Comment by Selur** [comment]
Thanks for looking into it. 👍

**Comment by WolframRhodium** [comment]
This is caused by overflow, and I have submitted a bug report to NVIDIA to enable per-layer precision controls.

**Comment by Selur** [comment]
just noticed: SCUNet with TensorRT and FP16 also gives me a green output (probably the same problem)

**Comment by WolframRhodium** [comment]
If you just updated the vs-mlrt runtime to v14, the SCUNet models should also be updated, otherwise a reproduction script is requested.

**Comment by Selur** [comment]
I'll redownload everything to be sure will report back. :)

**Comment by Selur** [comment]
Updating everything seems to have fixed the problem!
Thanks!
