### ISSUE TITLE
RIFE + scale broken?

### ISSUE THREAD

**Issue by Selur** [AmusementClub/vs-mlrt#94]
using:
```
clip = vsmlrt.RIFE(clip, multi=Fraction(2), model=44, backend=Backend.TRT(fp16=False,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1,builder_optimization_level=3,engine_folder="J:/tmp")) # new fps: 50
```
works fine, using adding scale=2.0:
```
clip = vsmlrt.RIFE(clip, multi=Fraction(2), model=44, scale=2.0, backend=Backend.TRT(fp16=False,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1,builder_optimization_level=3,engine_folder="J:/tmp")) # new fps: 50
```
I get:
```
Python exception: No module named 'onnx'

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
File "J:\tmp\tempPreviewVapoursynthFile15_57_05_583.vpy", line 48, in 
clip = vsmlrt.RIFE(clip, multi=Fraction(2), model=44, scale=2.0, backend=Backend.TRT(fp16=False,device_id=0,verbose=True,use_cuda_graph=False, num_streams=1,builder_optimization_level=3,engine_folder="J:/tmp")) # new fps: 50
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1154, in RIFE
output0 = RIFEMerge(
^^^^^^^^^^
File "F:/Hybrid/64bit/vs-mlrt/vsmlrt.py", line 1029, in RIFEMerge
import onnx
ModuleNotFoundError: No module named 'onnx'
```
using a different model doesn't help.

I saw:
```
  if (model_major, model_minor) >= (4, 7) and scale != 1.0:
        raise ValueError("not supported")
```
but for models < 4.7 it should work right?
(am I missing some models?)

**Comment by Selur** [comment]
Ah okay, I assumed everything would come with the downloads.
